version: '3.8'

services:
  backend:
    image: go-health-backend:1.0.0
    container_name: go-health-backend-container
    ports:
      - "8332:8332"
    restart: always

  frontend:
    image: go-health-ui:1.0.0
    container_name: go-health-ui-container
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
