name: go-health-app_service

networks:
  go-health-app:

services:
  go-health-app:
    image: ajaysc30/go-health-tracker:go-health-app-1.0.0
    container_name: go-health-app
    hostname: go-health-app
    networks:
      go-health-app:
    ports:
      - "8332:8332"

# docker compose up